#!/bin/bash

source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKUP THE SYSTEMD SERVICE
#=================================================

ynh_backup "/etc/systemd/system/$app.service"

#=================================================
# BACKUP THE DATABASE
#=================================================

if [ "${database:-}" == "mysql" ]; then
    ynh_print_info "Backing up MySQL database..."
    ynh_mysql_dump_db --database="$db_name" > ./db.sql
elif [ "${database:-}" == "postgresql" ]; then
    ynh_print_info "Backing up PostgreSQL database..."
    ynh_psql_dump_db --database="$db_name" > ./db.sql
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app."
