#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE .env FILE
#=================================================
ynh_script_progression "Updating configuration..."

sed -i "s|^DOMAIN=.*|DOMAIN=$new_domain|" "$install_dir/.env"
sed -i "s|^PATH_PREFIX=.*|PATH_PREFIX=$new_path|" "$install_dir/.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
